default: &default
  adapter: mysql2
  encoding: utf8   # ← 指示どおり utf8 に変更！
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:        # もしMySQLにパスワード設定してるならここに入力
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_45741_development

test:
  <<: *default
  database: protospace_45741_test

production:
  <<: *default
  database: protospace_45741_production
  username: root
  password: <%= ENV["PROTOSPACE_DATABASE_PASSWORD"] %>